plugin: aws_ec2
regions:
  - "eu-west-1"
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
