name: Build and deploy smart contract

on:
  push: 
    branches: 
      - main
      - deploy  
    paths:
      - "Task-2/Smart-contract-deployment/**"  

env:
  DEPLOY_DIRECTORY: "Task-2/Smart-contract-deployment/"

jobs:
  build: 
    name: Deploy HardHat
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x 

    - name: Smart Contract Deploy
      run: |
        cd $DEPLOY_DIRECTORY
        npm install
        npx hardhat run scripts/deploy-script.js --network kovan

    - name: Smart Contract Test
      run: |
        cd $DEPLOY_DIRECTORY
        npx hardhat test
